name: Build

on:
  push:
    tags:
      - 3.* # triggered on every push with tag 3.*
  workflow_dispatch: # or just on button clicked

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23.2
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.2"
        id: go

      - name: Setup Environments
        id: envs
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider

      - name: Setup QEMU Emulator
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          clean: false
          submodules: "recursive"
      - run: |
          git fetch --prune --unshallow --tags

      - name: Build and Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}