name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23.2
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build static files
        run: |
          mkdir assets/build
          touch assets/build/test.html

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
